### ISSUE TITLE
Identify Result Spacing

### ISSUE THREAD

**Issue by steveoh** [agrc/bb-econ#59]
Might be a css or template issue.
![image](https://cloud.githubusercontent.com/assets/325813/5927127/dadfcafc-a62d-11e4-9847-09e332d78948.png)

**Comment by stdavis** [comment]
I think this is a bug in xstyle as it doesn't exist in the unbuilt source. Looks like this rule:
```css
.current-location ul li:first-child {
    margin-left: 0;
}
```

is being minified to this:
```css
.current-location ul li {
    margin-left: 0;
}
